### ISSUE TITLE
Second search term interpreted as file

### ISSUE THREAD

**Issue by Flurrywinde** [alphapapa/mangle#1]
I ran: `mangle grep -H -i`, trying to highlight both the -H and -i options, but it seems to think `-H` is supposed to be a filename. Output:
```
$ mangle grep -H -i
grep: -H: No such file or directory
grep: -H: No such file or directory
```

**Comment by alphapapa** [comment]
Multiple search terms are not supported.  The command you entered is equivalent to `man grep -H | grep -- -i`.

**Comment by Flurrywinde** [comment]
Then I suggest changing the readme. It currently says, "You use it the same way as man, but you can add extra **words** after the name of the man page, and the man page will be grepped for those **words**."

Great little utility, BTW! (I am hacking it to default to regular `man` if there are no search terms (because my regular `man` is colored); allow multiple search terms; a way to grep something like `^\s*-i[ ,]`, where `-i` is an option you want to specifically search for; and a way to pull up just my own concise notes. I've been wanting something like this for a long time, just never thought to pipe man through grep.)

EDIT: boldify erroneous plurality in readme excerpt.

**Comment by alphapapa** [comment]
Thanks for pointing that out.  It's possible that I accidentally removed support for multiple search terms when I made some changes to the script before I published it here.  Or maybe it never supported multiple search terms.  I'm not sure.

Anyway, the change I just pushed should give the desired results for the `mangle grep -H -i` example you gave.  I should have thought of this myself, so thanks for reporting it.

> I am hacking it to default to regular man if there are no search terms (because my regular man is colored)

It should already do that, because it calls `command man`.  If it doesn't, I guess that would be a bug.  Or by "regular man" do you mean *not* `command man` but whatever `man` resolves to in your shell?

> a way to grep something like ^\s*-i[ ,], where -i is an option you want to specifically search for

I guess supporting actual regexps for searches wouldn't be too difficult to add.  Feel free to open an issue and we can talk about how best to do it.

Thanks.

**Comment by Flurrywinde** [comment]
>> I am hacking it to default to regular man if there are no search terms (because my regular man is colored)

> It should already do that, because it calls command man. If it doesn't, I guess that would be a bug. Or by "regular man" do you mean not command man but whatever man resolves to in your shell?

No, I do mean `command man`. Sorry, by "regular man" I meant not piping through `grep` or `less` because that strips out all colors, which I've added to `less` via the various $LESS_TERMCAP... environment variables. (See: https://wiki.archlinux.org/index.php/Color_output_in_console#less)

**Comment by alphapapa** [comment]
`less` need not strip out control characters.  See `less -r`.

**Comment by Flurrywinde** [comment]
Yes, but can `man` be made to send them? It seems to detect it's being piped, strips them, and doesn't have a `--color=always` option like other utilities, that I could find anyway.

**Comment by alphapapa** [comment]
AFAIK `man` doesn't have anything to do with color output.  Maybe you're using a different viewer, not "real" `man`?

**Comment by Flurrywinde** [comment]
That's what I always thought too until I saw some guy had colors on his man pages in some youtube video. I went hunting around, and it turns out it can actually have two additional text formats, originally bold and underline, which can be redefined to colors as described on the Arch wiki (see link above).
